import React from "react";
import { Roboto } from "next/font/google";
import Head from "next/head";
import Header from "./Header";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

function Layout({ children, pageTitle }: any) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>{pageTitle}</title>
      </Head>
      <Header />
      <main className={roboto.className}>{children}</main>
    </>
  );
}

export default Layout;
